// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5rnzD2-7u8dgSiyl3Xg7wwzAt2fm_x9M',
    appId: '1:546416114080:web:40e6dcf98897892090ccc5',
    messagingSenderId: '546416114080',
    projectId: 'voice-to-textnote',
    authDomain: 'voice-to-textnote.firebaseapp.com',
    storageBucket: 'voice-to-textnote.firebasestorage.app',
    measurementId: 'G-KXKGWLPM3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK_6Mz-WG1svjs-fuT3gXwiezp8snhs88',
    appId: '1:546416114080:android:65155b01c68cc13e90ccc5',
    messagingSenderId: '546416114080',
    projectId: 'voice-to-textnote',
    storageBucket: 'voice-to-textnote.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKfW0N33VpAMb16EZJDkxCwb9i3JekYeA',
    appId: '1:546416114080:ios:9aaacccd1a01c4fd90ccc5',
    messagingSenderId: '546416114080',
    projectId: 'voice-to-textnote',
    storageBucket: 'voice-to-textnote.firebasestorage.app',
    iosBundleId: 'com.voicetextnote.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKfW0N33VpAMb16EZJDkxCwb9i3JekYeA',
    appId: '1:546416114080:ios:8a6b8fa3836a78e290ccc5',
    messagingSenderId: '546416114080',
    projectId: 'voice-to-textnote',
    storageBucket: 'voice-to-textnote.firebasestorage.app',
    iosBundleId: 'com.voicetextnote.voiceToTextnote',
  );
}
